name: build
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Creates a production build of the app
        run: |
          sudo npm install -g @vue/cli
          rm -rf node_modules
          npm install
          npm run build
