name: e2e
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run start
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
