name: linter
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  linter:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Runs ESLint with the AirBnB styleguide
        run: |
          sudo npm install -g @vue/cli
          rm -rf node_modules
          npm install
          npm run lint
