name: unit
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Runs Jest unit-tests
        run: |
           sudo npm install -g @vue/cli
           rm -rf node_modules
           npm install
           npm run test:unit
